import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { Lora } from "next/font/google";
import { isDesktopApp } from "@/utils/desktop";
import { cn } from "@/utils/cn";
import "./globals.css";
import "@/styles/globals.css";

const lora = Lora({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDesktop = await isDesktopApp();
  return (
    <html lang="en" className={cn(isDesktop && "desktop")}>
      <body
        className={cn(
          `${GeistSans.variable} ${GeistMono.variable} ${lora.variable} font-sans`,
          "whitespace-pre-line overscroll-none antialiased",
        )}
      >
        {children}
      </body>
    </html>
  );
}
